name: auth_app
description: Demo app for authentication
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^8.0.0
  http_interceptor: ^1.0.2
  dio: ^5.1.2
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  http: ^0.13.6

flutter:
  uses-material-design: true

  assets:
    - .env